<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <Platforms>AnyCPU</Platforms>
    <AlgoType>Strategy</AlgoType>
    <AssemblyName>algoTrading</AssemblyName>
    <RootNamespace>algoTrading</RootNamespace>
    <StartAction>Program</StartAction>
    <StartProgram>C:\Quantower\TradingPlatform\v1.145.17\Console.StarterNew.exe</StartProgram>
    <StartArguments>--address 127.0.0.1 --port 58800</StartArguments>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <OutputPath>C:\Quantower\TradingPlatform\v1.145.17\..\..\Settings\Scripts\Strategies\algoTrading</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <OutputPath>C:\Quantower\TradingPlatform\v1.145.17\..\..\Settings\Scripts\Strategies\algoTrading</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="TradingPlatform.BusinessLayer">
      <HintPath>C:\Quantower\TradingPlatform\v1.145.17\bin\TradingPlatform.BusinessLayer.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>
</Project>